### ISSUE TITLE
Error  when starting server 1.1.15

### ISSUE THREAD

**Issue by krzyk79** [GetPerms/GetPerms#12] opened 2016-01-12 16:04 UTC
I am getting this error when i start the spigot server
also in the getperms plugin.yml file in the folder shows version GetPerms: 1.1.14
even though i downloaded the latest one 1.1.15

[09:57:52 INFO]: [GetPerms] Generating files...
[09:57:52 INFO]: [GetPerms] Compiled permission nodes into 'permission_nodes.txt' and
[09:57:52 INFO]: [GetPerms] 'permission_nodes_desc.txt' in plugins/GetPerms/.
[09:57:53 ERROR]: [GetPerms] An error has occurred! Please file an issue at
[09:57:53 ERROR]: [GetPerms] https://github.com/GetPerms/GetPerms/issues with the
[09:57:53 ERROR]: [GetPerms] below stack trace. Also, please include details about
[09:57:53 ERROR]: [GetPerms] what caused this error to occur.
[09:57:53 WARN]: java.io.FileNotFoundException: https://raw.githubusercontent.com/GetPerms/GetPerms/
master/db/WorldGuard/permission_nodes.txt
[09:57:53 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Sourc
e)
[09:57:53 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source
)
[09:57:53 WARN]:        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown
Source)
[09:57:53 WARN]:        at java.net.URL.openStream(Unknown Source)
[09:57:53 WARN]:        at com.github.GetPerms.GetPerms.Main.downloadFile(Main.java:251)
[09:57:53 WARN]:        at com.github.GetPerms.GetPerms.DatabaseDownloader.getPluginPermissions(Data
baseDownloader.java:44)
[09:57:53 WARN]:        at com.github.GetPerms.GetPerms.PermissionTask.run(PermissionTask.java:57)
[09:57:53 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)

[09:57:53 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbe
at(CraftScheduler.java:350)
[09:57:53 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:722)
[09:57:53 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[09:57:53 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653)
[09:57:53 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556
)
[09:57:53 WARN]:        at java.lang.Thread.run(Unknown Source)
[09:57:53 INFO]: [GetPerms] Permission lists generated!
[09:57:53 INFO]: [FastCraft] There are no available updates!
[09:57:58 INFO]: [GetPerms] GetPerms v1.1.15 is available.
[09:57:58 INFO]: [GetPerms] Downloading latest release build...
[09:57:58 INFO]: [GetPerms] The GetPerms update is located at
[09:57:58 INFO]: [GetPerms] 'plugins/GetPerms/update/GetPerms.jar'.

**Comment by Smiley43210** [comment] 2016-01-12 19:16
Thanks for reporting this! I have noted the incorrect version in config. The other error is a duplicate of #11.

**Comment by krzyk79** [comment] 2016-01-12 19:51
Thanks





Date: Tue, 12 Jan 2016 11:16:11 -0800

**Closed as completed** 2016-01-26 02:59 UTC
Labels: Accepted
